import{AI_PLAYER,MAX_ROUNDS,RECOVERY_LIMIT}from"./constants.js";
import{attackColor,attackDamage,cardLabel,drawToEight,initiativeValue,makeDeck,shuffle,sortCards}from"./cards.js";
import{aiPickInitiativeCard}from"../ai/ai.js";
export function initialGame(aiEnabled=true,aiLevel="basic"){let p1={name:"Italský hřebec",deck:makeDeck("P1"),hand:[],table:[]},p2={name:aiEnabled?(aiLevel==="hybrid"?"Muhammad AI":"Sparring partner"):"Zuřící býk",deck:makeDeck("P2"),hand:[],table:[]};p1=drawToEight(p1);p2=drawToEight(p2);return{players:[p1,p2],attacker:0,defender:1,phase:"initiative",round:1,maxRounds:MAX_ROUNDS,pausesThisRound:0,recoveryLimit:RECOVERY_LIMIT,viewingPlayer:0,pendingHandoff:false,selectedAttack:[],selectedBlock:null,selectedRecoverySuit:null,selectedInitiative:null,selectedInitiatives:[null,null],initiativePlayer:0,currentAttack:null,lastAttackColor:null,revealedInitiative:null,recoveryStarter:null,recoveryPlayer:null,winner:null,aiEnabled,aiLevel,damageFlash:null,log:["Nová hra. Vyber kartu pro iniciativu v 1. kole."]}}
export const withLog=(g,msg)=>({...g,log:[msg,...g.log].slice(0,16)});
export function activeHumanPlayer(g){if(g.phase==="initiative")return g.initiativePlayer??0;if(g.phase==="attack")return g.attacker;if(g.phase==="block")return g.defender;if(g.phase==="recovery")return g.recoveryPlayer;return 0}
export function finalizeTransition(prev,next){const active=activeHumanPlayer(next);return!next.winner&&!next.aiEnabled&&activeHumanPlayer(prev)!==active?{...next,viewingPlayer:active,pendingHandoff:true}:{...next,viewingPlayer:active,pendingHandoff:false}}
export function applyInitiativeSelection(g,picked){const picker=g.initiativePlayer??0,sel=[...(g.selectedInitiatives??[null,null])];sel[picker]=picked.id;if(!g.aiEnabled&&picker===0)return withLog({...g,selectedInitiatives:sel,selectedInitiative:null,initiativePlayer:1,viewingPlayer:1,pendingHandoff:true},`${g.players[0].name} vybral kartu pro iniciativu. Předej zařízení ${g.players[1].name}.`);const first=g.players[0].hand.find(c=>c.id===sel[0]),second=g.aiEnabled?aiPickInitiativeCard(g.players[AI_PLAYER].hand):g.players[1].hand.find(c=>c.id===sel[1]);if(!first||!second)return g;let starter=0;if(initiativeValue(second)>initiativeValue(first))starter=1;if(initiativeValue(first)===initiativeValue(second))starter=Math.random()<.5?0:1;return finalizeTransition(g,withLog({...g,phase:"attack",attacker:starter,defender:starter===0?1:0,viewingPlayer:starter,revealedInitiative:[first,second],selectedInitiative:null,selectedInitiatives:[null,null],initiativePlayer:0,selectedAttack:[],selectedBlock:null,currentAttack:null,lastAttackColor:null},`Iniciativa: ${cardLabel(first)} vs ${cardLabel(second)}. Začíná ${g.players[starter].name}.`))}
export function applyAttack(g,cards){const a=g.attacker,ids=new Set(cards.map(c=>c.id)),players=[...g.players];players[a]={...players[a],hand:sortCards(players[a].hand.filter(c=>!ids.has(c.id))),table:[...players[a].table,...cards]};return withLog({...g,players,phase:"block",currentAttack:cards,selectedAttack:[],selectedBlock:null},`${players[a].name} útočí: ${cards.map(cardLabel).join(" ")} — hrozí ${attackDamage(cards)} damage.`)}
export function applyUnblocked(g){const d=g.defender,damage=attackDamage(g.currentAttack),players=[...g.players],milled=players[d].deck.slice(0,damage);players[d]={...players[d],deck:players[d].deck.slice(milled.length),table:[...players[d].table,...milled]};const next={...g,players,phase:"attack",lastAttackColor:attackColor(g.currentAttack),currentAttack:null,selectedBlock:null,damageFlash:damage};if(milled.length<damage)return withLog({...next,winner:g.players[g.attacker].name},`${players[d].name} nemá dost karet na absorbování útoku. KO!`);return withLog(next,`${players[d].name} dostává zásah za ${damage} damage.`)}
export function applyBlock(g,block){const d=g.defender,players=[...g.players];players[d]={...players[d],hand:sortCards(players[d].hand.filter(c=>c.id!==block.id)),table:[...players[d].table,block]};const req=block.color==="red"?"černý":"červený";return withLog({...g,players,attacker:g.defender,defender:g.attacker,phase:"attack",lastAttackColor:block.color,currentAttack:null,selectedBlock:null,selectedAttack:[]},`${players[d].name} blokuje ${cardLabel(block)} a přebírá iniciativu. Další útok musí být ${req}.`)}
export function applyPause(g){const a=g.attacker,before=g.players[a].hand.length,players=[...g.players];players[a]=drawToEight(players[a]);const drawn=players[a].hand.length-before,base={...g,players,attacker:g.defender,defender:g.attacker,selectedAttack:[],lastAttackColor:null,pausesThisRound:g.pausesThisRound+1};if(base.pausesThisRound>=3)return withLog({...base,phase:"recovery",recoveryStarter:a,recoveryPlayer:a,selectedRecoverySuit:null},`${players[a].name} pauzíruje, líže ${drawn} a ukončuje kolo ${g.round}. Recovery začíná ${players[a].name}.`);return withLog(base,`${players[a].name} pauzíruje a líže ${drawn}.`)}
export function applyRecovery(g,recoverySuit){const idx=g.recoveryPlayer,p=g.players[idx],chosen=recoverySuit?p.table.filter(c=>c.suit===recoverySuit):[],ids=new Set(chosen.map(c=>c.id)),players=[...g.players];let np={...p,deck:shuffle([...p.deck,...chosen]),table:p.table.filter(c=>!ids.has(c.id))};const before=np.hand.length;np=drawToEight(np);const drawn=np.hand.length-before;players[idx]=np;const suitName=chosen.length?chosen[0].suitName:"žádný suit";if(idx===g.recoveryStarter){const other=idx===0?1:0;return withLog({...g,players,recoveryPlayer:other,selectedRecoverySuit:null},`${p.name} recoveruje ${suitName}: vrací ${chosen.length} karet a líže ${drawn}. Nyní recoveruje ${players[other].name}.`)}const nextRound=g.round+1;if(nextRound>g.maxRounds){const s0=players[0].table.length,s1=players[1].table.length,w=s0===s1?"Remíza":s0<s1?players[0].name:players[1].name;return withLog({...g,players,winner:w,recoveryPlayer:null,selectedRecoverySuit:null},`Konec zápasu. Skóre: ${s0}:${s1}.`)}return withLog({...g,players,round:nextRound,pausesThisRound:0,phase:"initiative",attacker:0,defender:1,selectedAttack:[],selectedBlock:null,selectedRecoverySuit:null,selectedInitiative:null,selectedInitiatives:[null,null],initiativePlayer:0,currentAttack:null,lastAttackColor:null,revealedInitiative:null,recoveryStarter:null,recoveryPlayer:null,viewingPlayer:0,pendingHandoff:false},`${p.name} recoveruje ${suitName}: vrací ${chosen.length} karet a líže ${drawn}. Kolo ${nextRound}: vyber kartu pro iniciativu.`)}
